# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - run: npm ci
    - run: npm test
      env:
        PORT: 7070
        SECRET: slkjfhglskdjf
        ENVIRONMENT: test
  
    - uses: akhileshns/heroku-deploy@v3.4.6 # This is the action
  
  deploy_stage:
    runs-on: ubuntu-latest
    needs: test
    with:
      heroku_api_key: ${{secrets.HEROKU_API_KEY}}
      heroku_app_name: ${{secrets.HEROKU_APP_NAME}} #Must be unique in Heroku
      heroku_email: ${{secrets.HEROKU_EMAIL}}
